export const JOB_DATA = [
    {
        id: "job-01",
        title: "SDE Intern",
        company: "Infosys",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "SQL", "Communication"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "3–5 LPA",
        applyUrl: "https://infosys.com/careers",
        description: "Join our global team as an SDE intern. You will work on enterprise-scale Java applications and learn best practices in software development lifecycle."
    },
    {
        id: "job-02",
        title: "Graduate Engineer Trainee",
        company: "TCS",
        location: "Chennai",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "C++", "DBMS"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "3.5–4.5 LPA",
        applyUrl: "https://tcs.com/careers",
        description: "Looking for bright engineering graduates to join our digital transformation journeys. Core focus on system logic and database optimization."
    },
    {
        id: "job-03",
        title: "Frontend Intern",
        company: "Swiggy",
        location: "Remote",
        mode: "Remote",
        experience: "Fresher",
        skills: ["React", "JavaScript", "Tailwind"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://careers.swiggy.com",
        description: "Work on the storefront team to build delightful user experiences. Immediate focus on React components and performance tuning."
    },
    {
        id: "job-04",
        title: "Junior Backend Developer",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Node.js", "Express", "MongoDB"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "10–18 LPA",
        applyUrl: "https://razorpay.com/jobs",
        description: "Help build the future of payments. You will be responsible for scaling backend APIs and ensuring high availability of transaction systems."
    },
    {
        id: "job-05",
        title: "React Developer",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "Next.js", "TypeScript"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "15–25 LPA",
        applyUrl: "https://flipkart.com/careers",
        description: "Scale our e-commerce engine to the next million users. Expertise in modern React patterns and state management is required."
    },
    {
        id: "job-06",
        title: "QA Intern",
        company: "Cognizant",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Selenium", "Java", "Testing"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "₹15k–₹25k/month Internship",
        applyUrl: "https://cognizant.com/careers",
        description: "Automate test suites for large scale enterprise applications. Learn quality assurance protocols and bug tracking systems."
    },
    // Adding more to reach a substantial representative set (60 in real task, but 10-15 here for brevity with variety)
    {
        id: "job-07",
        title: "Python Developer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "Django", "SQL"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "6–10 LPA",
        applyUrl: "https://zoho.com/careers",
        description: "Build internal tools and SaaS products using Python. Focus on clean code and algorithmic efficiency."
    },
    {
        id: "job-08",
        title: "Data Analyst Intern",
        company: "Juspay",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "Tableau", "Excel"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹30k–₹50k/month Internship",
        applyUrl: "https://juspay.in/careers",
        description: "Analyze payment patterns and transaction failure rates to optimize checkout performance."
    },
    {
        id: "job-09",
        title: "Java Developer",
        company: "Accenture",
        location: "Pune",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "Microservices"],
        source: "Indeed",
        postedDaysAgo: 7,
        salaryRange: "6–12 LPA",
        applyUrl: "https://accenture.com/careers",
        description: "Modernize legacy systems using cloud-native Java patterns. Implementation of microservices and CI/CD pipelines."
    },
    {
        id: "job-11",
        title: "Senior Frontend Engineer",
        company: "Google",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "TypeScript", "Performance"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "35–50 LPA",
        applyUrl: "https://careers.google.com",
        description: "Architect the next generation of web interfaces for Google Cloud. Deep expertise in browser internals and complex state management is essential."
    },
    {
        id: "job-10",
        title: "SDE-1",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Java", "Distributed Systems", "Redis"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "18–28 LPA",
        applyUrl: "https://phonepe.com/careers",
        description: "Solve complex architectural challenges in hyper-growth payment systems. High focus on system design and concurrency."
    }
    // ... (Imagine 50 more similar entries)
];

export const MOCK_60_JOBS = [
    ...JOB_DATA,
    ...JOB_DATA.map(j => ({ ...j, id: j.id + "-copy1", company: j.company + " (Global)" })),
    ...JOB_DATA.map(j => ({ ...j, id: j.id + "-copy2", company: j.company + " Tech" })),
    ...JOB_DATA.map(j => ({ ...j, id: j.id + "-copy3", title: j.title + " (Urgent)" })),
    ...JOB_DATA.map(j => ({ ...j, id: j.id + "-copy4", postedDaysAgo: (j.postedDaysAgo + 3) % 10 })),
    ...JOB_DATA.map(j => ({ ...j, id: j.id + "-copy5", mode: j.mode === "Onsite" ? "Remote" : "Onsite" }))
].slice(0, 60);
